<a href="https://colab.research.google.com/github/Bhandaram-Vasishta/Fire_Fire_prediction/blob/master/ForestFirePrediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import streamlit as st

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [6]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import warnings
import pickle
warnings.filterwarnings("ignore")

In [9]:
data = pd.read_csv("/content/drive/My Drive/Colab Notebooks/Forest/Forest_fire.csv")
data = np.array(data)

X = data[1:, 1:-1]
y = data[1:, -1]
y = y.astype('int')
X = X.astype('int')
print(X,y)


[[ 50  30  10]
 [ 10  20  70]
 [ 60  45  70]
 [ 30  48  10]
 [ 50  15  30]
 [  5  35  35]
 [  5  20  70]
 [ 60  32  19]
 [ 30  50  45]
 [ 40  55  80]
 [ 30  39 100]
 [ 10  12  12]
 [ 20  23  23]
 [ 60  34  15]
 [ 80   4  68]
 [ 25  56  79]
 [ 12  45  90]
 [ 28  43  15]
 [ 26   0  32]
 [ 32  37  21]
 [ 45  48  12]
 [ 56  15  65]
 [ 67  45  33]
 [ 78  49   8]
 [ 89  45  18]
 [ 21  12  44]
 [ 11  20  59]
 [  1  32  70]
 [  5  20  45]
 [ 42  43  20]
 [ 32  60  30]
 [  5  15   5]
 [ 20  30   5]
 [ 30  51   2]
 [ 60  60  10]
 [ 10  10  60]
 [  0  30   0]
 [ 45  45  15]] [1 0 1 1 0 0 0 1 1 1 0 0 0 1 0 1 0 1 0 1 1 0 1 1 1 0 0 0 0 1 1 0 0 1 1 0 0
 1]


In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
log_reg = LogisticRegression()


log_reg.fit(X_train, y_train)

pickle.dump(log_reg,open('model.pkl','wb'))

In [19]:
!pip install pyngrok

In [30]:
! ngrok authtoken XXXXXXX

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [67]:
%%writefile app.py
import streamlit as st
import pickle
import numpy as np
model=pickle.load(open('model.pkl','rb'))


def predict_forest(oxygen,humidity,temperature):
    input=np.array([[oxygen,humidity,temperature]]).astype(np.float64)
    prediction=model.predict_proba(input)
    pred='{0:.{1}f}'.format(prediction[0][0], 2)
    return float(pred)

def main():
    st.title("Streamlit Tutorial")
    html_temp = """
    <div style="background-color:#025246 ;padding:10px">
    <h2 style="color:white;text-align:center;">Forest Fire Prediction ML App </h2>
    </div>
    """
    st.markdown(html_temp, unsafe_allow_html=True)

    oxygen = st.text_input("Oxygen","Type Here")
    humidity = st.text_input("Humidity","Type Here")
    temperature = st.text_input("Temperature","Type Here")
    safe_html="""  
      <div style="background-color:#F4D03F;padding:10px >
       <h2 style="color:white;text-align:center;"> Your forest is safe</h2>
       </div>
    """
    danger_html="""  
      <div style="background-color:#F08080;padding:10px >
       <h2 style="color:black ;text-align:center;"> Your forest is in danger</h2>
       </div>
    """

    if st.button("Predict"):
        output=predict_forest(oxygen,humidity,temperature)
        st.success('The probability of fire taking place is {}'.format(output))

        if output > 0.5:
            st.markdown(danger_html,unsafe_allow_html=True)
        else:
            st.markdown(safe_html,unsafe_allow_html=True)

if __name__=='__main__':
    main()

Overwriting app.py


In [69]:
! ls
# ! streamlit run app.py &

app.py	drive  model.pkl  nohup.out  sample_data


In [70]:
!nohup streamlit run app.py &

nohup: appending output to 'nohup.out'


In [71]:
from pyngrok import ngrok

url=ngrok.connect(port='8501')

url

2020-09-07 13:00:17.189 INFO    pyngrok.process: ngrok process starting: 1483
2020-09-07 13:00:17.205 INFO    pyngrok.process: t=2020-09-07T13:00:17+0000 lvl=info msg="no configuration paths supplied"

2020-09-07 13:00:17.210 INFO    pyngrok.process: t=2020-09-07T13:00:17+0000 lvl=info msg="using configuration at default config path" path=/root/.ngrok2/ngrok.yml

2020-09-07 13:00:17.212 INFO    pyngrok.process: t=2020-09-07T13:00:17+0000 lvl=info msg="open config file" path=/root/.ngrok2/ngrok.yml err=nil

2020-09-07 13:00:17.217 INFO    pyngrok.process: t=2020-09-07T13:00:17+0000 lvl=info msg="starting web service" obj=web addr=127.0.0.1:4040

2020-09-07 13:00:17.646 INFO    pyngrok.process: t=2020-09-07T13:00:17+0000 lvl=info msg="tunnel session started" obj=tunnels.session

2020-09-07 13:00:17.647 INFO    pyngrok.process: t=2020-09-07T13:00:17+0000 lvl=info msg="client session established" obj=csess id=050365e3f9a2

2020-09-07 13:00:17.657 INFO    pyngrok.process: ngrok process has 

'http://36159d26c69f.ngrok.io'

2020-09-07 13:00:17.883 INFO    pyngrok.process: t=2020-09-07T13:00:17+0000 lvl=info msg=end pg=/api/tunnels id=c886ab86a4a8f1e2 status=201 dur=210.435832ms



In [68]:
ngrok.kill()

2020-09-07 13:00:10.778 INFO    pyngrok.process: Killing ngrok process: 1406
